### ISSUE TITLE
能看下SQL的建表吗？

### ISSUE THREAD

**Issue by shaoXunLu** [ZhengweiHou/carrentsystem#1]
我是新手，在您的项目里没看到传统的model式建模，也没找到SQL文件。希望您能联系我，这是我的QQ
790702057
再次希望您能联系我，谢谢

**Comment by ZhengweiHou** [comment]
@shaoXunLu sql文件已提交

**Comment by shaoXunLu** [comment]
我将项目在eclipse里打开，配好tomcat以后 发现lib目录下没有servlet.api.jar，此时可以访问index 页面，但所有涉及到servlet的页面（如登录）都无法访问。  lib下引入servlet 和jspjar包后，项目虽然不报错，但页面已无法访问（包括首页）

要用什么样正确的姿势打开您的项目呢？在线等

**Comment by shaoXunLu** [comment]
@

**Comment by shaoXunLu** [comment]
@ZhengweiHou

**Comment by ZhengweiHou** [comment]
项目没有问题可以运行，请检查你的容器，仔细调试，我用的tomcat7

**Comment by shaoXunLu** [comment]
嗯，谢谢 我在整整
